### ISSUE TITLE
References in headers

### ISSUE THREAD

**Issue by whazenberg** [StackVista/sts-agent#12]
Should name references in file/legal headers be tested by bamboo as well?

https://github.com/StackVista/sts-agent/blob/f5e70457b7ab28705d502e3f92c1d478762ef183/checks.d/kubernetes_state.py#L1

**Comment by raboof** [comment]
@whazenberg hi! could you unassign me? :)

**Comment by raboof** [comment]
oh - that's automatic by replying - cool!!

**Comment by whazenberg** [comment]
Cool, happy to help ;-)
